const booksData = [

    {
        title: "Ako nepodľahnúť diablovi",
        titleEn: "Outwitting the Devil",
        author: "Napoleon Hill, Sharon Lechterová",
        isbn: "978-80-89628-52-0",
        year: 2015,
        publisher: "Citadella",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 215,
        binding: "brožovaná",
        notes: ""
    },
        {
        title: "400 rád pre milovníkov psov",
        titleEn: "400 Tips for Dog Lovers",
        author: "Manfred Koch-Kostersitz",
        isbn: "-",
        year: 1973,
        publisher: "Príroda",
        category: "vzdelávanie",
        language: "slovenčina",
        pageCount: 95,
        binding: "pevná",
        notes: "poškodená"
    },
    {
        title: "Ako správne myslieť",
        titleEn: "As You Think",
        author: "James Allen, Vic Johnson",
        isbn: "978-80-8100-203-8",
        year: 2021,
        publisher: "Eugenika",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 168,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Almanach Navala Ravikanta",
        titleEn: "The Almanack of Naval Ravikant",
        author: "Eric Jorgenson",
        isbn: "978-80-99975-22-5",
        year: 2022,
        publisher: "Bajkal",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 240,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Biblia",
        titleEn: "The Bible",
        author: "Slovenská evanjelická cirkev v ČSSR",
        isbn: "0 564 03222 0",
        year: 1978,
        publisher: "Tranoscius",
        category: "duchovná",
        language: "slovenčina",
        pageCount: 1101,
        binding: "pevná",
        notes: "poškodená"
    },
    {
        title: "Brief answers to the big questions",
        titleEn: "Brief Answers to the Big Questions",
        author: "Stephen Hawking",
        isbn: "978-1-473-69598-6",
        year: 2018,
        publisher: "John Murray",
        category: "sebarozvoj",
        language: "angličtina",
        pageCount: 233,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Harryn Potter 1 Kameň mudrcov",
        titleEn: "Harry Potter and the Philosopher's Stone",
        author: "J. K. Rowlingová",
        isbn: "80-7118-971-5",
        year: 2000,
        publisher: "Ikar",
        category: "fantasy",
        language: "slovenčina",
        pageCount: 320,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Harryn Potter 2 Tajomná komnata",
        titleEn: "Harry Potter and the Chamber of Secrets",
        author: "J. K. Rowlingová",
        isbn: "80-551-0008-X",
        year: 2001,
        publisher: "Ikar",
        category: "fantasy",
        language: "slovenčina",
        pageCount: 360,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Harryn Potter 3 Väzeň z Azkabanu",
        titleEn: "Harry Potter and the Prisoner of Azkaban",
        author: "J. K. Rowlingová",
        isbn: "80-551-0046-2",
        year: 2001,
        publisher: "Ikar",
        category: "fantasy",
        language: "slovenčina",
        pageCount: 440,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Harryn Potter 4 Ohnivá čaša",
        titleEn: "Harry Potter and the Goblet of Fire",
        author: "J. K. Rowlingová",
        isbn: "978-80-551-4386-6",
        year: 2015,
        publisher: "Ikar",
        category: "fantasy",
        language: "slovenčina",
        pageCount: 712,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Imunita",
        titleEn: "Immune",
        author: "Philipp Dettmer",
        isbn: "978-80-222-1292-2",
        year: 2022,
        publisher: "Tatran",
        category: "vzdelávanie",
        language: "slovenčina",
        pageCount: 368,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Jak pěstovat konopí indoor 2.1",
        titleEn: "How to Grow Cannabis Indoors 2.1",
        author: "Josef Krejčík aka Mr. José",
        isbn: "978-80-907143-6-6",
        year: 2022,
        publisher: "Mosca Verde",
        category: "vzdelávanie",
        language: "čeština",
        pageCount: 415,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Malý princ",
        titleEn: "The Little Prince",
        author: "Antoine De Saint-Exupéry",
        isbn: "978-80-10-03466-6",
        year: 2023,
        publisher: "Mladé letá",
        category: "rozprávky",
        language: "slovenčina",
        pageCount: 96,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Myseľ bez hraníc",
        titleEn: "Limitless",
        author: "Jim Kwik",
        isbn: "978-80-222-1159-8",
        year: 2021,
        publisher: "Tatran",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 308,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Mysli a zbohatni",
        titleEn: "Think and Grow Rich",
        author: "Napoleon Hill",
        isbn: "978-80-8109-260-2",
        year: 2014,
        publisher: "Eastone Books",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 280,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Myšlienky k sebe samému",
        titleEn: "Meditations",
        author: "Marcus Aurelius Antoninus",
        isbn: "978-80-89520-23-7",
        year: 2015,
        publisher: "Thetis",
        category: "filozofia",
        language: "slovenčina",
        pageCount: 148,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Obyčajné zázraky",
        titleEn: "Ordinary Miracles",
        author: "Samuel Kováčik",
        isbn: "978-80-556-5046-3",
        year: 2021,
        publisher: "Slovart",
        category: "vzdelávanie",
        language: "slovenčina",
        pageCount: 240,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Prečo spíme",
        titleEn: "Why We Sleep",
        author: "Matthew Walker",
        isbn: "978-80-8182-110-3",
        year: 2018,
        publisher: "Citadella",
        category: "vzdelávanie",
        language: "slovenčina",
        pageCount: 412,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Psycho-kybernetika",
        titleEn: "Psycho-Cybernetics",
        author: "Maxwell Maltz",
        isbn: "978-80-8182-209-4",
        year: 2024,
        publisher: "Citadella",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 484,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Stála som pri bráne neba a pekla",
        titleEn: "Struck by Lightning",
        author: "Gloria Polo",
        isbn: "978-80-89676-98-9",
        year: 2016,
        publisher: "Zaex",
        category: "duchovná",
        language: "slovenčina",
        pageCount: 64,
        binding: "brožovaná",
        notes: ""
    },
    {
        title: "Zachovajte si bystrosť",
        titleEn: "Keep Sharp",
        author: "Sanjay Gupta",
        isbn: "978-80-222-1266-3",
        year: 2022,
        publisher: "Tatran",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 320,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Zo dňa ku hviezdam",
        titleEn: "From Day to the Stars",
        author: "Dušan Kadlec",
        isbn: "978-80-89977-06-2",
        year: 2019,
        publisher: "Motivation-Man",
        category: "sebarozvoj",
        language: "slovenčina",
        pageCount: 272,
        binding: "pevná",
        notes: ""
    },
    {
        title: "Zvieracia farma",
        titleEn: "Animal Farm",
        author: "George Orwell",
        isbn: "978-80-556-1084-9",
        year: 2013,
        publisher: "Slovart",
        category: "náučná",
        language: "slovenčina",
        pageCount: 101,
        binding: "pevná",
        notes: ""
    }
];
